-- Inserción de datos en la tabla provinces
INSERT INTO provinces (name, country_id) VALUES
('Buenos Aires', 1),
('Catamarca', 1),
('Chaco', 1),
('Chubut', 1),
('Córdoba', 1),
('Corrientes', 1),
('Entre Ríos', 1),
('Formosa', 1),
('Jujuy', 1),
('La Pampa', 1),
('La Rioja', 1),
('Mendoza', 1),
('Misiones', 1),
('Neuquén', 1),
('Río Negro', 1),
('Salta', 1),
('San Juan', 1),
('San Luis', 1),
('Santa Cruz', 1),
('Santa Fe', 1),
('Santiago del Estero', 1),
('Tierra del Fuego', 1),
('Tucumán', 1);

INSERT INTO provinces (name, country_id) VALUES
('Chuquisaca', 2),
('Cochabamba', 2),
('El Beni', 2),
('La Paz', 2),
('Oruro', 2),
('Pando', 2),
('Potosí', 2),
('Santa Cruz', 2),
('Tarija', 2);

INSERT INTO provinces (name, country_id) VALUES
('Acre', 3),
('Alagoas', 3),
('Amapá', 3),
('Amazonas', 3),
('Bahia', 3),
('Ceará', 3),
('Distrito Federal', 3),
('Espírito Santo', 3),
('Goiás', 3),
('Maranhão', 3),
('Mato Grosso', 3),
('Mato Grosso do Sul', 3),
('Minas Gerais', 3),
('Pará', 3),
('Paraíba', 3),
('Paraná', 3),
('Pernambuco', 3),
('Piauí', 3),
('Rio de Janeiro', 3),
('Rio Grande do Norte', 3),
('Rio Grande do Sul', 3),
('Rondônia', 3),
('Roraima', 3),
('Santa Catarina', 3),
('São Paulo', 3),
('Sergipe', 3),
('Tocantins', 3);

INSERT INTO provinces (name, country_id) VALUES
('Arica y Parinacota', 4),
('Tarapacá', 4),
('Antofagasta', 4),
('Atacama', 4),
('Coquimbo', 4),
('Valparaíso', 4),
('Región Metropolitana de Santiago', 4),
('O\'Higgins', 4),
('Maule', 4),
('Ñuble', 4),
('Biobío', 4),
('La Araucanía', 4),
('Los Ríos', 4),
('Los Lagos', 4),
('Aysén', 4),
('Magallanes', 4);

INSERT INTO provinces (name, country_id) VALUES
('Amazonas', 5),
('Antioquia', 5),
('Arauca', 5),
('Atlántico', 5),
('Bolívar', 5),
('Boyacá', 5),
('Caldas', 5),
('Caquetá', 5),
('Casanare', 5),
('Cauca', 5),
('Cesar', 5),
('Chocó', 5),
('Córdoba', 5),
('Cundinamarca', 5),
('Guainía', 5),
('Guaviare', 5),
('Huila', 5),
('La Guajira', 5),
('Magdalena', 5),
('Meta', 5),
('Nariño', 5),
('Norte de Santander', 5),
('Putumayo', 5),
('Quindío', 5),
('Risaralda', 5),
('San Andrés y Providencia', 5),
('Santander', 5),
('Sucre', 5),
('Tolima', 5),
('Valle del Cauca', 5),
('Vaupés', 5),
('Vichada', 5);

INSERT INTO provinces (name, country_id) VALUES
('Azuay', 6),
('Bolívar', 6),
('Cañar', 6),
('Carchi', 6),
('Chimborazo', 6),
('Cotopaxi', 6),
('El Oro', 6),
('Esmeraldas', 6),
('Galápagos', 6),
('Guayas', 6),
('Imbabura', 6),
('Loja', 6),
('Los Ríos', 6),
('Manabí', 6),
('Morona Santiago', 6),
('Napo', 6),
('Orellana', 6),
('Pastaza', 6),
('Pichincha', 6),
('Santa Elena', 6),
('Santo Domingo de los Tsáchilas', 6),
('Sucumbíos', 6),
('Tungurahua', 6),
('Zamora Chinchipe', 6);

INSERT INTO provinces (name, country_id) VALUES
('Alto Paraguay', 7),
('Alto Paraná', 7),
('Amambay', 7),
('Asunción', 7),
('Boquerón', 7),
('Caaguazú', 7),
('Caazapá', 7),
('Canindeyú', 7),
('Central', 7),
('Concepción', 7),
('Cordillera', 7),
('Guairá', 7),
('Itapúa', 7),
('Misiones', 7),
('Ñeembucú', 7),
('Paraguarí', 7),
('Presidente Hayes', 7),
('San Pedro', 7);

INSERT INTO provinces (name, country_id) VALUES
('Amazonas', 8),
('Áncash', 8),
('Apurímac', 8),
('Arequipa', 8),
('Ayacucho', 8),
('Cajamarca', 8),
('Callao', 8),
('Cusco', 8),
('Huancavelica', 8),
('Huánuco', 8),
('Ica', 8),
('Junín', 8),
('La Libertad', 8),
('Lambayeque', 8),
('Lima', 8),
('Loreto', 8),
('Madre de Dios', 8),
('Moquegua', 8),
('Pasco', 8),
('Piura', 8),
('Puno', 8),
('San Martín', 8),
('Tacna', 8),
('Tumbes', 8),
('Ucayali', 8);
